### ISSUE TITLE
BLIS Overview

### ISSUE THREAD

**Issue by annchemu** [geoflen/iBLIS_UGANDA#22]
There are minor issues in the system, mostly errors due to missing variable, but it's in a good shape .

1. Error when adding duplicate values in Surveillance rather than showing an alert informing the user that the value already exists in DB
2. The buttons to update or to generate a config file for an interface equipment not working. There is no action done
3. Reports
     i. User statistics - Data warning alerts (from data-tables) when there is nothing to view in the report type
    ii. Reports - Error when View Report button is clicked after choosing the Control

Minor issues
1. Save Button in the Create Test Type page is floating outside the margin
2. Deleting a drug in use, the alert says 'Successfully deleted' while the drug is still there. Consider changing the alert

**Comment by ereng** [comment]
All these change significantly on the branch that counts "develop", apologies for not clarifying before hand
