### ISSUE TITLE
Develop Branch Review

### ISSUE THREAD

**Issue by annchemu** [geoflen/iBLIS_UGANDA#23]
Good morning,

Some tables seem to be missing from the migration such as specimen_unhls in the UnhlsSpecimen Model and tests table.

This affects the Tests and Reports modules in the system

**Comment by ereng** [comment]
done a little fix up there, @annchemu kindly keep the comments coming, we could keep this issue open for the moment.

**Comment by ereng** [comment]
anyone following up on this, remember to adjust database configs of your local machine and run `composer dumpautoload`

**Comment by ereng** [comment]
There is a duplicate of models UnhlsTest and Test, fixing now...

**Comment by ereng** [comment]
Start test is failing because of confusing the two

**Comment by ereng** [comment]
Edit results failing `Class TestController does not exist`

**Comment by ereng** [comment]
Am closing this issue, more specific ones can be created
