### ISSUE TITLE
Report Controller 

### ISSUE THREAD

**Issue by annchemu** [geoflen/iBLIS_UGANDA#24]
Hi @ereng ,

In the Report Controller, the Test model is still in use in most of the functions starting from the daily log rather than UnhlTest model. 

They also still refer to the tests table in the database rather than the unhl_tests table.

Consider editing the controller to reflect your new changes.

**Comment by ereng** [comment]
So true! thanks @annchemu, over to you... @geoflen while you work on the reports.

**Comment by geoflen** [comment]
Thanks @annchemu pushing changes in a bit
