### ISSUE TITLE
RRT > tests requests failing

### ISSUE THREAD

**Issue by ereng** [geoflen/iBLIS_UGANDA#8]
To reproduce error, on the menu click *RRT*, on its submenu click *Test Requests*

`Class 'UnhlsTest' not found`

**Comment by ereng** [comment]
@geoflen are you in position to check on this, and guide on the best solution(*that does not create other breakages*)

**Comment by geoflen** [comment]
Pull again .....had not pushed this particular Class

**Comment by ereng** [comment]
Just pulled...(its up to date) and still failing, will keep checking to see if the problem is local

**Comment by geoflen** [comment]
Same error?

**Comment by ereng** [comment]
yap

**Comment by ereng** [comment]
Any fix for this yet?
